### PR TITLE
Add support for crystal 0.27.0

### PR DESCRIPTION
**Pull request by mang**
Using `File` since `Tempfile` is removed

### CODE REVIEW

**Comment by imdrasil** [comment]
Thnx for the PR :+1:  Please also update the `im_version` in the `.travis.install_imagemagick.sh` from `7.0.8-8` to `7.0.8-14` - this will fix the failed build.

**Comment by mang** [comment]
Oh thanks! Travis got past it now, but I realised now the tests fails at:
 ```
CryMagick::Image::#format#test_works_without_an_extension_with_new [spec/crymagick/image_spec.cr:324]:
Expected ".png" but got ""
```
Any ideas why that is?

**Comment by imdrasil** [comment]
As far as I can see this is because `File.tempfile` and `File.tempname` has slightly different logic behind file name generating. Tomorrow will add an update with fixing this.

**Comment by imdrasil** [comment]
the actual reason was a bug in the `CryMagick::Image#new` method )

**Review by imdrasil — APPROVED** [review]

**Pull request merged**
